// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_VKfCFIufxpmUtBmlnrucq2euDkLLM8',
    appId: '1:687845921833:web:26a694832bd9d465317838',
    messagingSenderId: '687845921833',
    projectId: 'bloom-15fd9',
    authDomain: 'bloom-15fd9.firebaseapp.com',
    storageBucket: 'bloom-15fd9.firebasestorage.app',
    measurementId: 'G-BTXC98GWC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGlDvdjYKdQxY_kQsVCulE3X18xHVXZDg',
    appId: '1:687845921833:android:623bf90d39e55eb9317838',
    messagingSenderId: '687845921833',
    projectId: 'bloom-15fd9',
    storageBucket: 'bloom-15fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrRx8VYjKad1FTFsejnKLgCk-zXu59QJE',
    appId: '1:687845921833:ios:5ca2f897d18b5dcd317838',
    messagingSenderId: '687845921833',
    projectId: 'bloom-15fd9',
    storageBucket: 'bloom-15fd9.firebasestorage.app',
    iosClientId: '687845921833-9le60aq51tpr8pmv0gg7mk9kur73771b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrRx8VYjKad1FTFsejnKLgCk-zXu59QJE',
    appId: '1:687845921833:ios:5ca2f897d18b5dcd317838',
    messagingSenderId: '687845921833',
    projectId: 'bloom-15fd9',
    storageBucket: 'bloom-15fd9.firebasestorage.app',
    iosClientId: '687845921833-9le60aq51tpr8pmv0gg7mk9kur73771b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4_VKfCFIufxpmUtBmlnrucq2euDkLLM8',
    appId: '1:687845921833:web:26a694832bd9d465317838',
    messagingSenderId: '687845921833',
    projectId: 'bloom-15fd9',
    authDomain: 'bloom-15fd9.firebaseapp.com',
    storageBucket: 'bloom-15fd9.firebasestorage.app',
    measurementId: 'G-BTXC98GWC8',
  );
}
